// bomberfish
// JIT.h – Limon
// created on 2023-11-29

#ifndef JIT_h
#define JIT_h

#import <Foundation/Foundation.h>
#import <mach-o/dyld.h>
#import <spawn.h>
#import <sys/sysctl.h>

// generated by fucking chatgpt
extern char** environ;

int csops(pid_t pid, unsigned int ops, void *useraddr, size_t usersize);
CFTypeRef SecTaskCopyValueForEntitlement(void* task, NSString* entitlement, CFErrorRef  _Nullable *error);
void* SecTaskCreateFromSelf(CFAllocatorRef allocator);
int ptrace(int, pid_t, caddr_t, int);
void saveIntValueToUserDefaults(int value, NSString *key);
BOOL getEntitlementValue(NSString *key);
BOOL isJITAlreadyEnabled(BOOL checkCSFlags);
void ShowAlert(NSString* title, NSString* message);
int enableTSJIT(int argc, char **argv);


#endif /* JIT_h */
